---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: index.html
  label: Edit Main Page
upload_dir: img
public_path: "/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: starefossen/github-pages
  mount_path: public
  working_dir: "/srv"
  instant_preview_command: npm run forestry:preview
